### ISSUE TITLE
Data_label unit is missing in BaseFitPlugin

### ISSUE THREAD

**Issue by gudlot** [hereon-GEMS/pydidas#52]
When testing a workflow that includes the BaseFitPlugin, the unit in the data_label of the Dataset is missing, when "Test workflow" is executed a second time. 

![Screenshot_pydidas](https://github.com/user-attachments/assets/fe4c77fd-2142-4105-bcd7-9ad40b2c72aa)

Steps to reproduce:
1. Implement workflow (see image)
2. In `Test workflow` press `Process frame`
3. Press `Process frame` a second time. Here the unit is missing in data_label of the Dataset.

I discovered this bug by using print statements in the BaseFitPlugin at the beginning and at the end within the `execute`-method.

First run of frame 62:

🌴🌴🌴🌴🌴🌴🌴🌴 BaseFitPlugin in 🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴
ds Dataset(
axis_labels: {
    0: 'd-spacing'},
axis_ranges: {
    0: array([0.301118, 0.30095 , 0.300782, ..., 0.193422, 0.193353, 0.193283])},
axis_units: {
    0: 'nm'},
metadata: {},
data_unit: counts,
data_label: integrated intensity,
array([3.617439, 4.881439, 5.037748, ..., 3.000473, 3.008927, 2.305964],
      dtype=float32)
)
🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴
🌴🌴🌴🌴🌴🌴🌴🌴 BaseFitPlugin out 🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴
_results Dataset(
axis_labels: {
    0: '0: position; 1: area; 2: FWHM; 3: background at peak; 4: total count
       intensity'},
axis_ranges: {
    0: array([0, 1, 2, 3, 4])},
axis_units: {
    0: ''},
metadata: {'fit_func': 'Voigt', 'fit_params': {'amplitude':
   0.5433902446667973, 'sigma': 0.0010278518499551158, 'gamma':
   0.001118397888375067, 'center': 0.2104072320985986, 'background_p0':
   2.4840039849403395}, 'fit_residual_std': 0.04394456285064119},
data_unit: ,
**data_label: position / nm; area / (cts * nm); FWHM / nm; background at peak / cts; total count intensity / cts,**
array([2.104072e-01, 5.433902e-01, 3.830186e-03, 2.484004e+00,
       7.320281e+03])
)
🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴

Second run of frame 62: 

🌴🌴🌴🌴🌴🌴🌴🌴 BaseFitPlugin in 🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴
ds Dataset(
axis_labels: {
    0: 'd-spacing'},
axis_ranges: {
    0: array([0.301118, 0.30095 , 0.300782, ..., 0.193422, 0.193353, 0.193283])},
axis_units: {
    0: 'nm'},
metadata: {},
data_unit: counts,
data_label: integrated intensity,
array([3.617439, 4.881439, 5.037748, ..., 3.000473, 3.008927, 2.305964],
      dtype=float32)
)
🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴
🌴🌴🌴🌴🌴🌴🌴🌴 BaseFitPlugin out 🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴
_results Dataset(
axis_labels: {
    0: '0: position; 1: area; 2: FWHM; 3: background at peak; 4: total count
       intensity'},
axis_ranges: {
    0: array([0, 1, 2, 3, 4])},
axis_units: {
    0: ''},
metadata: {'fit_func': 'Voigt', 'fit_params': {'amplitude':
   0.5433902446667973, 'sigma': 0.0010278518499551158, 'gamma':
   0.001118397888375067, 'center': 0.2104072320985986, 'background_p0':
   2.4840039849403395}, 'fit_residual_std': 0.04394456285064119},
data_unit: ,
**data_label: position; area; FWHM; background at peak; total count intensity,**
array([2.104072e-01, 5.433902e-01, 3.830186e-03, 2.484004e+00,
       7.320281e+03])
)
🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴

**Comment by malte-storm** [comment]
Fixed with #53
