### ISSUE TITLE
Missing information in documentation for Dataset

### ISSUE THREAD

**Issue by gudlot** [hereon-GEMS/pydidas#57]
The documentation for Dataset is here [https://hereon-gems.github.io/pydidas/versions/24.06.05/code/api/core/dataset.html#pydidas.core.Dataset.mean](https://hereon-gems.github.io/pydidas/versions/24.06.05/code/api/core/dataset.html#pydidas.core.Dataset.mean)

Currently the link under [source] seems to be broken. Should it not lead to 
[https://github.com/hereon-GEMS/pydidas/blob/6617e31d0b055416248ff1b935d7c162dea0f1d9/pydidas/core/dataset.py#L57](https://github.com/hereon-GEMS/pydidas/blob/6617e31d0b055416248ff1b935d7c162dea0f1d9/pydidas/core/dataset.py#L57)
?

I was also looking for pydidas.Dataset.mean doc.
I can find `[pydidas.core.Dataset.mean](https://hereon-gems.github.io/pydidas/code/api/core/dataset.html#pydidas.core.Dataset.mean)` in the search, but there are currently no further explanation about this function.

**Comment by malte-storm** [comment]
The link points to the website source code, not the code sourcecode and is part of the pydata sphinx theme. It works as intended.
