### ISSUE TITLE
 DeprecationWarning: __array_wrap__ Method in Dataset Class

### ISSUE THREAD

**Issue by gudlot** [hereon-GEMS/pydidas#58]
I have encountered a DeprecationWarning while running tests with pytest. The warning indicates that the `__array_wrap__` method in the `Dataset` class does not accept the `context` and `return_scalar` arguments, which will be required in the future versions of NumPy (Deprecated NumPy 2.0). 

```
tests/_plugin_tests/proc_plugins/test_stress_strain.py: 10 warnings
 .../pydidas/pydidas/core/dataset.py:913: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
    _new = ndarray.squeeze(self, axis)
```

Environment:
Operating System: macOS 
Python Version: Python 3.12.4
NumPy Version: 2.0.0 
pytest Version: 8.3.1

**Comment by malte-storm** [comment]
Fixed with #59
